[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:backend]
command=java -jar /opt/market-shop/app.jar
directory=/opt/market-shop
priority=10
autostart=true
autorestart=true
startsecs=10
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -c /opt/market-shop/nginx.conf -g "daemon off;"
priority=20
autostart=true
autorestart=true
startsecs=2
startretries=5
stopsignal=QUIT
stopasgroup=true
killasgroup=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
