<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminApi, money } from '../api'
type Dashboard={memberCount:number;todayOrderCount:number;todayCompletedAmountFen:number;pendingSuperiorCount:number;pendingReviewCount:number;pendingShipCount:number;activeAfterSaleCount:number;onSaleProductCount:number;lowInventorySkuCount:number}
const data=ref<Dashboard>();const error=ref('')
onMounted(async()=>{try{data.value=await adminApi<Dashboard>('/dashboard')}catch(e){error.value=(e as Error).message}})
</script>
<template><div v-if="data"><div class="page-title"><div><h1>业务概览</h1><p>线下订单、会员、履约和售后的实时运营指标。</p></div><span class="tag green">系统运行中</span></div><p v-if="error" class="error">{{error}}</p><section class="metrics"><div class="card"><span>会员总数</span><b>{{data.memberCount}}</b><small>商城会员账号</small></div><div class="card"><span>今日订单</span><b>{{data.todayOrderCount}}</b><small>含全部状态</small></div><div class="card"><span>今日完成订单额</span><b>{{money(data.todayCompletedAmountFen)}}</b><small>不代表在线收款</small></div><div class="card"><span>在售商品</span><b>{{data.onSaleProductCount}}</b><small>低库存 {{data.lowInventorySkuCount}} 个</small></div></section><section class="dashboard-grid"><div class="card task-card"><h2>工作队列</h2><RouterLink to="/orders"><span class="queue-icon coral">审</span><div><b>等待后台审核</b><small>直属上级已确认线下收款</small></div><strong>{{data.pendingReviewCount}} →</strong></RouterLink><RouterLink to="/orders"><span class="queue-icon green">发</span><div><b>等待仓库发货</b><small>已审核通过</small></div><strong>{{data.pendingShipCount}} →</strong></RouterLink><RouterLink to="/after-sales"><span class="queue-icon gold">售</span><div><b>进行中售后</b><small>可能触发积分冲正</small></div><strong>{{data.activeAfterSaleCount}} →</strong></RouterLink></div><div class="card boundary"><span>合规边界</span><h2>积分不是现金。</h2><p>积分禁止提现、转账或兑换现金。奖励关系深度固定为一层；订单首次完成后才生成任务证据。</p><RouterLink to="/rules">查看规则版本 →</RouterLink></div></section></div>
</template>
<style scoped>.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.metrics .card{padding:20px}.metrics span,.metrics b,.metrics small{display:block}.metrics span{color:var(--muted)}.metrics b{font:750 28px serif;margin:9px 0}.metrics small{color:#929b96}.dashboard-grid{display:grid;grid-template-columns:1.4fr .6fr;gap:16px;margin-top:16px}.task-card,.boundary{padding:24px}.task-card h2{font-family:serif}.task-card a{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:center;padding:15px 0;border-top:1px solid var(--line)}.task-card small{display:block;color:var(--muted);margin-top:4px}.queue-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:11px}.coral{background:#fbe6e1}.green{background:#e3efea}.gold{background:#fff0cf}.boundary{color:white;background:#31594e}.boundary>span,.boundary a{color:#f2b88f}.boundary p{color:#ffffffad;line-height:1.8}@media(max-width:1000px){.metrics{grid-template-columns:repeat(2,1fr)}.dashboard-grid{grid-template-columns:1fr}}@media(max-width:520px){.metrics{grid-template-columns:1fr}}</style>
